# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      
      # instalar as dependencias com NPM/YARN
      - name: Install dependencies
        run: yarn
      
      # Exceutar a Build
      - name: Run build
        run: yarn build
      
      # Copiar a pasta dist para a digitalOcean
      - name: copy dist folder to digitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/app/gobarber-back-end"

      # executar as migrations do typeorm e Restart o servidor node
      - name: Run productions scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/gobarber-back-end
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart gobarber-api
            
